{{ PREFIXES }}

SELECT DISTINCT ?reliability ?item ?factorloading ?reversed ?subdim ?subreliability ?subitem ?subfactorloading ?subreversed WHERE {
  {% if graph %}
  OPTIONAL {
    GRAPH <{{ graph }}> { <{{ uri }}> owsom:chronbachAlpha ?reliability . }
  }
  {% endif %}
  { 
    GRAPH ?g1 { <{{ uri }}> owsom:hasItem ?item . }
    
    {% if graph %}
    OPTIONAL {
      GRAPH <{{ graph }}> { ?item owsom:hasFactorLoading ?factorloading . }
    }
    {% endif %}
    OPTIONAL {
      GRAPH ?2 { ?item owsom:isReversed ?reversed . }
    }
  }
  UNION
  {
    GRAPH ?g3 { 
      <{{ uri }}> owsom:hasDimension ?subdim . 
  	  ?subdim owsom:hasItem ?subitem . 
    } 
    {% if graph %}
    OPTIONAL {
      GRAPH <{{ graph }}> { ?subdim owsom:chronbachAlpha ?subreliability . }
    }
    {% endif %}
    {% if graph %}
    OPTIONAL {
      GRAPH <{{ graph }}> { ?subitem owsom:hasFactorLoading ?subfactorloading . }
    }
    {% endif %}
    OPTIONAL {
      GRAPH ?g4 { ?subitem owsom:isReversed ?subreversed .}
    }
  }
}