{{PREFIXES}}

SELECT DISTINCT ?scale ?label ?type ?type_label WHERE {
  GRAPH ?g {
    ?scale rdfs:label ?label .
   {
     ?scale a owsom:LikertScale .
     BIND(owsom:LikertScale as ?type )
     BIND("Likert Scale" as ?type_label )
   } UNION {
     ?scale a owsom:GuttmanScale .
     BIND(owsom:GuttmanScale as ?type )
     BIND("Guttman Scale" as ?type_label )
   } UNION {
     ?scale a owsom:SemanticDifferentialScale .
     BIND(owsom:SemanticDifferentialScale as ?type )
     BIND("Semantic Differential Scale" as ?type_label )
   }
 }
}


